### ISSUE TITLE
NIO based Stripe Client

### ISSUE THREAD

**Issue by Andrewangeta** [vapor-community/stripe-provider#98]

**Comment by Andrewangeta** [comment]
**TODO**
Implement the following APIs:
- [ ]  Events
- [x] PaymentIntents
- [x] Sessions
- [x] Usage records
- [x] Application fee refunds
- [x] Application fees
- [x] Country Specs
- [x] External Accounts
- [x] Top-Ups
- [x] Reviews
- [x] Value lists
- [x] Value lists items
- [x] Connection Tokens
- [x] Locations
- [x] Readers
- [x] Scheduled queries
- [ ] Webhook endpoints

Cleanup:
- [x] Remove `total_count` from all lists.
- [x] Add folder structure to reflect [Stripes API](https://stripe.com/docs/api) as well as the README
- [x] Remove coding keys from models and use `convertFromSnakeCase`in latest swift linux release
- [x] Coding keys for custom decoding should be private enums not public
- [x] Adopt `EventLoopFuture` naming convention.
- [x] Full documentation for API routes. [see here for example](https://github.com/vapor-community/stripe-provider/blob/21fbcc7088be87a404ab5b3654d2daa6991aaff0/Sources/Stripe/API/Routes/PersonRoutes.swift#L10-L43)
- [x] Document Models with their link to Stripes API
- [x] Consistent naming of Models (Still open to ideas) Either `STPModelName` or `StripeModelName`
- [x] Remove `AnyDecodable` and model types from route parameters in favor of `[String: Any]` (Since it's more flexible and Stripes API changes frequently)
- [x] ALOT of documentation for scenarios/flows not immediately obvious in API.
- [x] Rely on Swift 5

**Comment by anthonycastelli** [comment]
I think you've covered everything here so far 👍 If I think of anything I'll add it in 😊

**Comment by Andrewangeta** [comment]
This has been addressed with [StripeKit](https://github.com/vapor-community/stripe-kit)
